### ISSUE TITLE
Tray quit not work on MacOS 

### ISSUE THREAD

**Issue by chuyingy** [UofA-SPI21-team7/Zettlr#59]
Tray quit function is not working if the following steps applied on MacOS: 
1. Click the `Open...` button
2. Click Tray -> `Quit` when the file browser window is opening, quit is not working
3. Close the file browser window, Tray -> `Quit` still no longer works.

- [ ] Please also test these steps on the Windows and Linux platforms.
- [ ] Please check whether this issue is brought by our implementation.

**Comment by cskeogh** [comment]
This is an existing bug in Zettlr. To reproduce with `develop` branch:

1. Click the `Open...` button
2. `⌘ Q` when the file browser window is open, quit is not working
3. Close the file browser window, `⌘ Q` and `Zettlr` ➔ `Quit` no longer works.

Because this is an existing bug, I don't think we have to fix part of `issue175`

**Comment by cskeogh** [comment]
This bug does not occur on Windows or Linux - Gnome desktop.

**Comment by cskeogh** [comment]
I think this is a bug in electron. See electron/electron#28927
